AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources:
  CreateShortLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-create-short-link
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      CodeUri: src/createShortLink
      Description: "Creates a new short link"
      Timeout: 15
      Role: arn:aws:iam::388474961170:role/lambda-admin
  CreateOwnedShortLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-create-owned-short-link
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      CodeUri: src/createOwnedShortLink
      Description: "Creates a new user-owned short link"
      Timeout: 15
      Role: arn:aws:iam::388474961170:role/lambda-admin
  ShortLinkRedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-short-link-redirect
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      CodeUri: src/shortLinkRedirect
      Description: "Redirects request based off short link from URL path"
      Timeout: 5
      Role: arn:aws:iam::388474961170:role/lambda-admin
  GetOwnedShortLinksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-get-owned-short-links
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      CodeUri: src/getOwnedShortLinks
      Description: "Gets all short links owned by calling user"
      Timeout: 5
      Role: arn:aws:iam::388474961170:role/lambda-admin
  CloseAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-close-account
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      CodeUri: src/closeAccount
      Description: "Closes a user's account"
      Timeout: 5
      Role: arn:aws:iam::388474961170:role/lambda-admin
