AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources:
  CloseAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-close-account
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/closeAccount
      Description: "Closes a user's account"
      Timeout: 5
      Role: arn:aws:iam::388474961170:role/lambda-admin
  CreateLinkCollectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-create-link-collection
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/createLinkCollection
      Description: "Creates a new link collection"
      Timeout: 15
      Role: arn:aws:iam::388474961170:role/lambda-admin
  CreateOwnedShortLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-create-owned-short-link
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/createOwnedShortLink
      Description: "Creates a new user-owned short link"
      Timeout: 15
      Role: arn:aws:iam::388474961170:role/lambda-admin
  CreateShortLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-create-short-link
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/createShortLink
      Description: "Creates a new short link"
      Timeout: 15
      Role: arn:aws:iam::388474961170:role/lambda-admin
  DeleteLinkCollectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-delete-link-collection
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/deleteLinkCollection
      Description: "Deletes a link collection"
      Timeout: 15
      Role: arn:aws:iam::388474961170:role/lambda-admin
  DeleteOwnedShortLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-delete-owned-short-link
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/deleteOwnedShortLink
      Description: "Deletes a user-owned short link"
      Timeout: 15
      Role: arn:aws:iam::388474961170:role/lambda-admin
  GetLinkCollectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-get-link-collection
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/getLinkCollection
      Description: "Gets a link collection"
      Timeout: 15
      Role: arn:aws:iam::388474961170:role/lambda-admin
  GetOwnedLinkCollectionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-get-owned-link-collections
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/getOwnedLinkCollections
      Description: "Gets all link collections owned by calling user"
      Timeout: 5
      Role: arn:aws:iam::388474961170:role/lambda-admin
  GetOwnedShortLinksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-get-owned-short-links
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/getOwnedShortLinks
      Description: "Gets all short links owned by calling user"
      Timeout: 5
      Role: arn:aws:iam::388474961170:role/lambda-admin
  GetUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-get-user-data
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/getUserData
      Description: "Gets user data for calling user"
      Timeout: 5
      Role: arn:aws:iam::388474961170:role/lambda-admin
  GetShortLinkStatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-get-short-link-stats
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/getShortLinkStats
      Description: "Calculates and returns aggregate short links stats"
      Timeout: 15
      Role: arn:aws:iam::388474961170:role/lambda-admin
  ShortLinkRedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-short-link-redirect
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/shortLinkRedirect
      Description: "Redirects request based off short link from URL path"
      Timeout: 5
      Role: arn:aws:iam::388474961170:role/lambda-admin
  UpdateLinkClickCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-update-link-click-count
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/updateLinkClickCount
      Description: "Increments the click count for a collection's link"
      Timeout: 5
      Role: arn:aws:iam::388474961170:role/lambda-admin
  UpdateLinkCollectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-update-link-collection
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/updateLinkCollection
      Description: "Updates a link collection"
      Timeout: 15
      Role: arn:aws:iam::388474961170:role/lambda-admin
  UpdateUserDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-update-user-data
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/updateUserData
      Description: "Updates a user's data"
      Timeout: 15
      Role: arn:aws:iam::388474961170:role/lambda-admin
  UpdateOwnedShortLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: st-update-owned-short-link
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: src/updateOwnedShortLink
      Description: "Updates a user-owned short link's redirect URL"
      Timeout: 15
      Role: arn:aws:iam::388474961170:role/lambda-admin
