title: "SeeTh.is"
email: "tjharrisonjr@gmail.com"
description: "Short-links and Link Collections"
baseurl: ""
url: "https://terryjharrison.github.io"
logo: "https://seeth.is/logo192.png"

theme: just-the-docs
mermaid:
  # Available versions at https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

aux_links:
  "SeeTh.is":
    - "https://seeth.is"

nav_external_links:
  - title: "OpenAPI Specifications"
    url: "https://terryjharrison.github.io/see-this-api/swagger-ui"