title: "SeeTh.is"
email: "tjharrisonjr@gmail.com"
description: "Short-links and Link Collections"
baseurl: ""
url: "https://terryjharrison.github.io"
logo: "https://seeth.is/logo192.png"

theme: just-the-docs
plugins:
  - jekyll-mermaid
mermaid:
  src: "https://unpkg.com/mermaid@9.2.2/dist/mermaid.js"

aux_links:
  "SeeTh.is":
    - "https://seeth.is"